### ISSUE TITLE
Composability Questions

### ISSUE THREAD

**Issue by beardedtim** [stephenlcurtis/hypatia#1]
As I was looking through the `maths` module, I came across [these](https://github.com/stephenlcurtis/hypatia/blob/master/src/maths.js#L43-L75) definitions of _n_-ary functions. This is a great use of the `spread`/`rest` operator but it does not lend itself to composing these operators with the result of past ones. 

For instance, to use `subtract` and then `add`, from my understanding of the code, I would need to:

```
const a = 1;
const b = 2;
const c = 3;

const added = add(a, b);
const subtracted = subtract(added, c);
```

This works and is great but it doesn't go with how the rest of my system operates. Instead, could the API be:

```
const subtract = a => b => a - b; // your awesome sub here but only with 2 options
const add = a => b => a + b; // your awesome math here

// Somewhere in my code
const mySpecficUseCase = compose(
  subtract(c)
  add(a)
)
// Somewhere else in my code.
const mySpecificAnswer = mySpecificUseCase(b);
```

This way, we use unary functions that compose with Ramda, lodash/fp, functional toolkits.

This does mean that you can't have any amount of values ( as you currently have with `...values` ) so if your use-case is that you specifically need to be able to pass in `pow(1,2,3,4,5,....)` instead of creating a HoF to do that, then my advice above is moot. 

What do you think? Would making this more composable be worth the effort?

**Comment by stephcurt** [comment]
I really like the idea making a high order unary such that it's composable. My only issue is one of the main things these functions have to do it double as grouping operators in pretty complicated equations, [here's one of them](https://github.com/stephenlcurtis/hypatia/blob/master/src/geometry.js#L171-L180) but more will be added in the physics and trig modules.

So not just the grouping, but the readability aspect. I can easily read that as `a + -3at + 3at^2 - at^3 + 3bt - 6bt^2 + 3bt^3 + 3ct^2 -3ct^3 + dt^3` for example.

Ideally the API to be unary and spread at the same time; And if it's composable? Then an IoC container as well for chainability. The main reason for this extensibility would be both readability and the monadic approach I'd like to take with the draw loop.

**Comment by stephcurt** [comment]
I am thinking a good step would actually to be to convert the math module to unaries but have wrappers that use those unaries and allow for the spread implementation. This should allow them to still be composable with a unary library?

**Comment by beardedtim** [comment]
>  convert the math module to unaries but have wrappers that use those unaries and allow for the spread implementation.

This is what I was thinking but wasn't sure the best way to express that idea!

This way, you can create the complicated equation as a wrapper/function that calls the smaller utility functions that you made ( add, subtract, multiply, etc ). 

So if you wanted to add a list of numbers, you could:

```
const myAdd = curry((a, b) => a + b);
const addMyList = reduce(myAdd, 0);
const myList = [1, 2, 3];
addMyList(myList);
```

This way your utility functions can be chained/composed but you can still use them with a list, like you wanted. [Here](http://ramdajs.com/repl/#?const%20myAdd%20%3D%20curry%28%28a%2C%20b%29%20%3D%3E%20a%20%2B%20b%29%3B%0Aconst%20addMyList%20%3D%20reduce%28myAdd%2C%200%29%3B%0Aconst%20myList%20%3D%20%5B1%2C%202%2C%203%5D%3B%0AaddMyList%28myList%29%3B) is a ramda pen that shows using this via Ramda but I am sure you could write your own `curry` or `reduce` methods if you wanted to keep this dep free!

**Comment by beardedtim** [comment]
Using the compose/curry take, in my experience, allows not only you as the lib author to refactor/change/update the codebase but also allows the consumers of this codebase to use it outside of the context you imagined while still offering a contract that the code works as expected.

**Comment by stephcurt** [comment]
Okay we're on the same page, I was actually testing out using curry/reduce to figure out the best way to do this. Because there are different rules in some cases for order and what not depending on operation custom reduces will be needed in some cases.

**Comment by stephcurt** [comment]
I think forgoing chainability and keeping the equations compositional in format makes the most sense, chainability now seems like an unnecessary complexity.

**Comment by stephcurt** [comment]
Although if the project ends up needing IoC containers that may change.

**Comment by stephcurt** [comment]
@beardedtim I updated the maths library and added unit tests with these two commits:

[here](https://github.com/stephenlcurtis/hypatia/commit/9de2395ca09e4b20c9bdd202c6198248fc9e6a4a)
[here](https://github.com/stephenlcurtis/hypatia/commit/2f0136c24b48477c83ba6f50a4ee7d5ce3dd8d53)
[here](https://github.com/stephenlcurtis/hypatia/commit/8de6609395620894d271e6fb6cf7ffcb7f8db836)
[and here](https://github.com/stephenlcurtis/hypatia/commit/df6ab7ecc5b51b2bafb64d4ef71afaea9b04b67b)

Please review and let me know what you think. I also added the ability to specify the number of decimal places to control accuracy to via composition rather than a config file setting.  I also peeled this off into its own math library here: https://github.com/stephenlcurtis/maths.js, once I get it into NPM I'll just change it in this project to a reference.

**Comment by stephcurt** [comment]
Nomenclature: plus, minus, times, over, exp are the unary functions. add, subtract, divide, multiply, pow are the spread wrappers that can take n args and perform the operation across all of them.
