### ISSUE TITLE
Geometry Module Questions

### ISSUE THREAD

**Issue by beardedtim** [stephenlcurtis/hypatia#2]
Gonna jot these down while I'm perusing the `./modules/geometry` file. I'll be sure to check back and add in-depth replies/explanations if need be!

* [These lines](https://github.com/stephenlcurtis/hypatia/blob/master/src/geometry.js#L25-L29) make sense on why you would use those symbols (delta/gamma/the math stuff). But I find that it is just a pain in butt having to use those. As the consumer of this module, I would want it spelled out in my native language ( English ) rather than cryptic symbols. You can still use `Symbol('whatever')` but the `this.altCodeThatIHaveToTypeEveryTime` would be really annoying and prone to user-error

* [These](https://github.com/stephenlcurtis/hypatia/blob/master/src/geometry.js#L56-L61) lines use Symbol as well but I am not 100% that they should. I can see the use in being able to check equality against a single value but I have not ran into an instance where passing a string value wasn't acceptable where a Symbol was. But that's a coding style choice more than anything I think so 👍 

* [This](https://github.com/stephenlcurtis/hypatia/blob/master/src/geometry.js#L98) function has a tad too many parameters for me to feel safe using it without constantly looking at the docs/definition. I would make this into an object ( `{ x, y, z, ...}` ) so that I could pass in these values in any "order" and it still work. 

Besides that, this file looks great! A little dense but your JSDOC comments are very helpful! Keep up the great work!

**Comment by stephcurt** [comment]
On the cryptic symbols I completely agree, I'll replace with alphanumeric strings (phi, theta, etc.) and push the symbols to the... Symbols.

I am still unsure about Symbol vs strings. Which do you think is more readable to people developing with the module?

Understood on object vs lots of arguments. I'll make that change.

**Comment by beardedtim** [comment]
I dislike symbol because it acts like a string except it isn't one. I always end up turning them into strings when I want to start building a bigger or different abstraction. 

I feel like Symbol is just not helpful enough in my coding experience to warrant giving up the flexibility of a string.

**Comment by stephcurt** [comment]
I understand. Since I don't really have a good reason to use them outside of a specific need to have a globally unique value or actually represent a non-ascii symbol, that's a pretty clear indication they aren't an improvement.
